### ISSUE TITLE
Still crashing on 1.3.5 pojav zenith horizon

### ISSUE THREAD

**Issue by OverScarf** [MovTery/ZalithLauncher#171]
### Issue Type / 问题类型

Application Issue / 应用问题

### Issue Description / 问题描述

Still crashing in 1.3.5 pojav zenith and can't play 

### Log File / 日志文件

[latestlog.txt](https://github.com/user-attachments/files/17354602/latestlog.txt)

### Screenshots or Videos / 截图或视频

https://github.com/user-attachments/assets/583ab378-55f3-4c58-851d-e7a9e029e6e3

### Android Version / Android 版本

13

### App Version / 应用版本

1.3.5

### Selected Renderer / 选择的渲染器

None

### Device Information / 设备信息

Poco F1 android13 arm64 sdm845

### This issue has not been reported before / 这个问题还没有人反馈过

- [X] I have checked the Issues and found no similar issue reported / 我已经查看过 Issues，并且没有发现与之类似的问题被反馈

**Comment by MovTery** [comment]
Please select Fabric when creating the instance, choose the Minecraft 1.21 version, then select Fabric Loader version 0.16.0. After downloading and installing the installer, select JRE 8, and then wait for Fabric to install, which will complete the missing files.

**Comment by MovTery** [comment]
After the installation is complete, please remember to use the new instance to avoid encountering other issues.

**Comment by OverScarf** [comment]
> After the installation is complete, please remember to use the new instance to avoid encountering other issues.

Would I clear all data and reinstall alla files will it fix the crashing issue ?

**Comment by MovTery** [comment]
Generally, you only need to completely delete the .minecraft folder because all the game files are stored here. After deleting it, reinstall a new instance, and the files will be downloaded again. You can give it a try.

![IMG_20241013_152228](https://github.com/user-attachments/assets/99a6fc8e-81c0-4b15-b724-9b778d6e3b1c)

Additionally, this will result in the deletion of your game saves, resource packs, and mods, as they are also stored here. Therefore, you need to make a backup in advance.

**Comment by OverScarf** [comment]
Still crashing mahn can you give your discord mine is OverScarf525870#6290
[latestlog.txt](https://github.com/user-attachments/files/17355004/latestlog.txt)
